<TidesScreen>:
    Label:
        pos: 0, 130
        text: "[size=120]{type:s} {h:02d}:{m:02d}[/size]".format(**root.prev)
        markup: True

    Label:
        pos: 0, 0
        text: "[size=70]{h:02d}:{m:02d}[/size][size=50] {s:02d}[/size]".format(**root.timedata)
        markup: True

    Label:
        pos: 0, -130
        text: "[size=120]{type:s} {h:02d}:{m:02d}[/size]".format(**root.next)
        markup: True
